### ISSUE TITLE
Chapter 3, Control flow: "If loop"

### ISSUE THREAD

**Issue by mateon1** [psibi/rust-book-summary#1]
https://github.com/psibi/rust-book-summary/blob/master/README.md#if-loop

This should probably say something else, like "Conditional", "if-else construct", or whatever you prefer.

**Comment by mateon1** [comment]
`if let` and the `match` construct are also missing from this section.

**Comment by psibi** [comment]
@mateon1 Thanks for the catch!

> This should probably say something else, like "Conditional", "if-else construct", or whatever you prefer

I agree. I think we can change it to "If Expressions` - similar to how it is in the book. Do you want to send a PR for the same ?

> if let and the match construct are also missing from this section.

They are explained as part of chapter 6, so I didn't include it here.

* `if let`: https://github.com/psibi/rust-book-summary/blob/master/README.md#if-let
* `match`: https://github.com/psibi/rust-book-summary/blob/master/README.md#match-control-flow-operator

**Comment by mateon1** [comment]
Sorry, I won't have access to a computer I can comfortably code on for the next 6 hours or so. I just made a quick issue after skimming a few chapters.

Regarding `if let` and `match`, if they were all in the same section, this would make a nice reference you could link beginners to.

**Comment by psibi** [comment]
> Sorry, I won't have access to a computer I can comfortably code on for the next 6 hours or so. I just made a quick issue after skimming a few chapters.

Unless you aren't planning to work on it, I will fix it myself. But if it's a matter of 6 hours, I can wait. :-) No hurries!

> Regarding if let and match, if they were all in the same section, this would make a nice reference you could link beginners to.

The reason they are in chapter 6 is because it shows how `match` and `if let` is used on an enum type. And `enum` is introduced only on chapter 6.

**Comment by mateon1** [comment]
Feel free to do it yourself, I think that will just be simpler.

**Comment by psibi** [comment]
@mateon1 Thanks for the report! Fixed it by changing it to `If Expressions`.
